-- CREATE TYPE "public"."action_type" AS ENUM('create', 'update', 'delete', 'upload', 'login', 'logout', 'import', 'export');
--> statement-breakpoint
-- CREATE TYPE "public"."client_type" AS ENUM('client', 'provider', 'both');
--> statement-breakpoint
-- CREATE TYPE "public"."currency_position" AS ENUM('before', 'after');
--> statement-breakpoint
-- CREATE TYPE "public"."decimal_separator" AS ENUM(',', '.');
--> statement-breakpoint
-- CREATE TYPE "public"."fiscal_period" AS ENUM('calendar', 'may_april');
--> statement-breakpoint
-- CREATE TYPE "public"."invoice_class" AS ENUM('A', 'B', 'C');
--> statement-breakpoint
-- CREATE TYPE "public"."invoice_type" AS ENUM('income', 'expense', 'neutral');
--> statement-breakpoint
-- CREATE TYPE "public"."payment_status" AS ENUM('pending', 'paid', 'overdue', 'cancelled');
--> statement-breakpoint
-- CREATE TYPE "public"."review_status" AS ENUM('approved', 'pending_review', 'draft');
--> statement-breakpoint
-- CREATE TYPE "public"."rounding_mode" AS ENUM('round', 'ceil', 'floor');
--> statement-breakpoint
-- CREATE TYPE "public"."thousand_separator" AS ENUM('.', ',', ' ', 'none');
--> statement-breakpoint
-- CREATE TYPE "public"."upload_job_status" AS ENUM('queued', 'processing', 'success', 'duplicate', 'error');
-- --> statement-breakpoint
-- CREATE TYPE "public"."user_role" AS ENUM('admin', 'editor', 'viewer');
-- --> statement-breakpoint
-- CREATE TABLE "activity_logs" (
--     "id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
--     "user_id" varchar NOT NULL,
--     "user_name" text NOT NULL,
--     "action_type" "action_type" NOT NULL,
--     "entity_type" text NOT NULL,
--     "entity_id" varchar,
--     "description" text NOT NULL,
--     "metadata" text,
--     "ip_address" text,
--     "created_at" timestamp DEFAULT now() NOT NULL
-- );
-- --> statement-breakpoint
-- ... (resto de las tablas y tipos de datos comentados) ...
ALTER TABLE "invoices" ALTER COLUMN "fingerprint" SET DATA TYPE varchar(64);
--> statement-breakpoint
ALTER TABLE "invoices" ALTER COLUMN "fingerprint" SET NOT NULL;